{ ... }:
{
  imports = [
    ./android-tools.nix
    ./easyeffects
    #./firefox.nix
    ./file-roller.nix
    ./fonts.nix
    #./git.nix
    ./ghostty.nix
    ./gparted.nix
    ./grim.nix
    ./gwenview.nix
    ./gimp.nix
    #./libreoffice.nix
    ./kitty.nix
    ./musescore.nix
    ./marktext.nix
    ./neovim.nix
    ./nix-direnv.nix
    ./nautilus.nix
    ./obsidian
    ./okular.nix
    ./pavucontrol.nix
    ./qbittorrent.nix
    ./ranger.nix
    ./shells
    #./spotify.nix
    ./stylix.nix
    ./slurp.nix
    ./ssh.nix
    ./telegram.nix
    ./term2alpha.nix
    ./vlc.nix
    ./virtmanager.nix
    ./ventoy.nix
    ./vscode.nix
    ./wpsoffice.nix
    ./wezterm.nix
    ./slurp.nix
    ./spicetify.nix
    ./tmux.nix
    ./zed.nix
    ./zen-browser.nix
  ];
}
