{ ... }:
{
  imports = [
    ./android-tools.nix
    ./easyeffects
    #./firefox.nix
    ./git.nix
    ./ghostty.nix
    ./gparted.nix
    ./grim.nix
    #./libreoffice.nix
    ./neovim.nix
    ./nautilus.nix
    ./obsidian
    ./okular.nix
    ./pavucontrol.nix
    ./qbittorrent.nix
    ./ranger.nix
    ./shells
    ./spotify.nix
    ./stylix.nix
    ./slurp.nix
    ./telegram.nix
    ./vlc.nix
    ./virtmanager.nix
    ./ventoy.nix
    ./vscode.nix
    ./wpsoffice.nix
    ./slurp.nix
    ./zen-browser.nix
  ];
}
